### ISSUE TITLE
something wrong

### ISSUE THREAD

**Issue by Garhorne0813** [sudalvxin/2019-PR-Sparse-Multi-view-clustering#2]
Sorry, your code is running incorrectly. I wonder if there are some documents missing, or if my operation is wrong.

`***********The test datas name is: ***5***ORL.mat****************
函数或变量 'constructW' 无法识别。

出错 Test_SMVSC (line 20)
    A0 = constructW(X{i},options);

出错 Test_allData (line 19)
result = Test_SMVSC(X,Y,paraset{data_num});`

**Comment by wenbolics** [comment]
少个函数叫constructW.m
